name: Build Asteroids with Pygbag
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-pygbag:
    runs-on: ubuntu-latest
    name: Build Asteroids with Pygbag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirement.txt

      - name: Install pygbag
        run: |
          pip install pygbag

      - name: Build Pygbag
        run: |
          pygbag build .

      - name: Upload Pygbag
        uses: actions/upload-artifact@v4
        with:
          name: pygbag-asteroids
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          commit_message: "Deploy Pygbag to GitHub Pages"
          commit_options: --no-verify
          enable_jekyll: false
          enable_page_build: false
          enable_push: true